In [54]:
import numpy as np

In [34]:
np.array([10,20,24,5,15,50,89])

array([10, 20, 24,  5, 15, 50, 89])

In [35]:
a = np.array([10, 30, 7, 45, 89, 56, 25, 32])
a[4]

89

In [36]:
a[3:]

array([45, 89, 56, 25, 32])

In [37]:
a[3:6]

array([45, 89, 56])

In [38]:
a[1::2]

array([30, 45, 56, 32])

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
ones = np.ones((4,5)) #Creación de una matriz
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
type(ones)

numpy.ndarray

In [42]:
type(ones[3,1])

numpy.float64

In [43]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [44]:
b = np.array([['x', 'y', 'z'], ['a', 'b', 'c']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'b' 'c']]


numpy.ndarray

In [45]:
b.ndim #Ver las dimensiones

2

In [46]:
c = [12, 54, 1, 6, 74, 8, 98, 54, 52]
np.sort(c) # Ordenamiento de datos

array([ 1,  6,  8, 12, 52, 54, 54, 74, 98])

In [47]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype=cabeceras)
np.sort(usuarios, order = 'edad') #Ordenar datos con respecto a la edad

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [48]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
np.arange(5, 30) #Límite inferior a superior

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
np.arange(5, 50, 5) #Límite inferior, superior y el paso del avance

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [51]:
np.full((3, 5), 10) #Creacion de una matriz indicando el tamaño y los datos que va a contener

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [52]:
np.diag([0, 3, 9, 10]) #Una matriz de forma diagonal con los valores indicados

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [53]:
headers = [('nombre','S10'), ('edad', int), ('nacionalidad','S100')]
data = [('Amelie',21,'Francesa'), 
         ('Valerie', 30,'Canadiense'),
         ('Valentina',25,'Inglesa'),
         ('Alejandra',22,'Cubana')]
users = np.array(data,dtype=headers)
np.sort(users, order = 'nacionalidad')

array([(b'Valerie', 30, b'Canadiense'), (b'Alejandra', 22, b'Cubana'),
       (b'Amelie', 21, b'Francesa'), (b'Valentina', 25, b'Inglesa')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('nacionalidad', 'S100')])